apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-incident-config
  namespace: default

data:
  ENV: "production"
  BACKEND_URL: "http://backend-service:8000"
  FRONTEND_URL: "http://frontend-service:80"
  LOG_LEVEL: "info"